### ISSUE TITLE
Problem activating plugin

### ISSUE THREAD

**Issue by githubarbiter** [AlexaCRM/integration-dynamics#10]
Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '[' in /home/content/95/9478795/html/wp-content/plugins/integration-dynamics/integration-dynamics.php on line 115

I can't find the errant "[" in the code.

Thoughts?

**Comment by georged** [comment]
@githubarbiter Can you please confirm version of PHP your WordPress is running on? Note that as per https://wordpress.org/plugins/integration-dynamics/ we only support PHP 5.4 and above.

**Comment by githubarbiter** [comment]
Brilliant, thanks. After upgrading PHP, the plugin activated without error.

 

Have a great weekend, and thanks for your swift resolution of our issue!
