### ISSUE TITLE
Could not find definition of Service <DiscoveryService> in provided WSDL 

### ISSUE THREAD

**Issue by eohm** [AlexaCRM/integration-dynamics#11]
In trying to research the error, it looks like it starts with Dynamics 8.2

**Comment by georged** [comment]
@eohm can you email organization url to support@alexacrm.com so that we can investigate? We don't have any issues accessing 8.2 organizations.

**Comment by eohm** [comment]
sent the email per your request.  I get the same error on 2 organizations.

**Comment by georged** [comment]
@eohm as per our communications, issue is resolved by checking "Ignore certificate errors" checkbox. We'll be investigating what's causing these CRM certificates to suddenly become non-trusted, as far as WordPress is concerned.
