### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by Ashish225** [AlexaCRM/integration-dynamics#12]
I got this error while activating plugin:

Parse error: syntax error, unexpected '[' in /home/toaraich/andaze.com/public_html/wp-content/plugins/integration-dynamics/integration-dynamics.php on line 115

**Comment by georged** [comment]
@Ashish225 

please check your PHP version. We support version 5.4 and above.

Thanks
AlexaCRM
