### ISSUE TITLE
Configuration won't stick

### ISSUE THREAD

**Issue by veedubb8** [AlexaCRM/integration-dynamics#13]
I have now attempted three different browsers to connect the CRM plugin to my CRM. All information is correct in the set-up, but when I click connect, it either provides a 500 error in Chrome, a blank page in Firefox, or a "cannot display the page" error in IE.  Seems like this free plugin is too good to be true....

**Comment by georged** [comment]
Hi @veedubb8 

sorry about the issue. Can you tell us a bit more: version of plugin, version of WordPress, php version. 

What would really help if you can send us a screenshot of the connection settings before you press the connect button. 

Also, on About tab there is a path to the log file(s) - if you can get some of those to us (if available) that'd help as well.

If concerned about the privacy, please email screenshots and logs to support@alexacrm.com

Thanks
George

**Comment by veedubb8** [comment]
Hi George,

Thank you for getting back to me so quickly!

·         version of plugin – 1.1.32.1

·         version of WordPress – 4.7.3

·         php version - 5.5.9-1ubuntu4.21

·         Screenshot of connections:

[cid:image002.jpg@01D2B8F0.289F3530]


I will have to ask an admin to get me the log files. I don’t think I have access.


Sean Cahill | Central Support Manager | Car Toys, Inc. |
p: 206-626-8964  | m: 206.450.4371| f: 425-650-8443 | e: scahill@cartoys.com<mailto:scahill@cartoys.com>
Individualization • Achiever • Relator •Ideation • Intellection
Please note: New Cell Phone Number: 206.450.4371

This email and any attached files transmitted with are confidential or otherwise protected by work product confidentiality or other legal rules and intended solely for the use of the individual or entity to which they are addressed.  If you are not the named addressee you should not disseminate, distribute, or copy this email or attachment.  Please notify the sender immediately by email if you have received this email by mistake, and then delete this email from your system.  If you are not the intended recipient you are hereby notified that disclosing, copying, distributing, or taking any action in reliance on the content of this information is strictly prohibited.

WARNING: Computer viruses can be transmitted via email.  The recipient should check this email and any attachments for the presence of viruses.  The Company accepts no liability for any damage caused by any virus transmitted or received by this email.

**Comment by georged** [comment]
Hi Sean

image didn't make it :/ (but heaps of other private info did so I truncated your reply above). Can you please send the screenshot directly to support@alexacrm.com? 

Thanks
George

**Comment by veedubb8** [comment]
done
