### ISSUE TITLE
Question: Can it send existing user to CRM?

### ISSUE THREAD

**Issue by Bobolions** [AlexaCRM/integration-dynamics#14]
Looks like a great plugin. Can it send (or sync / overwrite) existing WP users (and user meta data) to the CRM?

**Comment by georged** [comment]
Hi @Bobolions 

this plugin itself does not deal with authentication. We do have [premium addon](https://alexacrm.com/premium) that connects WordPress users and CRM entities (typically contacts but can be anything, actually). Once premium addon is installed and activated, the following needs to be done:

1. Export WP users in bulk (as CSV) and importing them into WP Identity entity in CRM (part of our solution)
2. Marking WP users as linked to CRM - can be done in builk in WordPress. 

In this scenario there are no changes to how users log in. However, the above steps ensure that every time the WP user logs in, CRM is notified and responds with the confirmation that the user is a valid one and returns an entity correposnding to the WP user. This entity record is available in the templates as `currentuser`, e.g. `currentuser.fullname`, etc

HTH
George
