### ISSUE TITLE
I am using plugin to add a form in my site and it works fine but it sends 3 duplicate data to to my crm records

### ISSUE THREAD

**Issue by SplitView** [AlexaCRM/integration-dynamics#15]

**Comment by georged** [comment]
Hi @SplitView 

someone else reported a [`similar issue`](https://wordpress.org/support/topic/creating-leads-in-triplicate/). I trust that you don't have any plugins or workflows on the target entity in CRM.

I wonder if it's related to some third-party plugin... 

Would you mind sending to support@alexacrm.com some additional information: 

- log file (location is specified on About tab)
- list of the active plugins in your WordPress install
- theme used for the site

Also, as a quick test, can you add a form for a different entity and test it. Do you get those records in triplicate as well? (If not, that'd be then a side effect of something in CRM, if yes then it's on the WordPress side of things )

Thanks
George

**Comment by SplitView** [comment]
I am using Kleo Theme, the plugins installed are BuddyPress,	
Custom CSS and Javascript, Dynamics 365 Integration, Easy Testimonials, GoDaddy Reseller Store, Google Analytics for WordPress by MonsterInsights, If Menu, 	
K Elements, Postman SMTP, Redirection, 	
Slider Revolution, 	
Social Pug, TM WooCommerce Compare & Wishlist, WooCommerce, WooCommerce esewa, Wordfence Security, WP-Mail-SMTP, WPBakery Visual Composer
log: https://1drv.ms/f/s!AhX7seYMjLvNziXZ8ztDtnXerR4c
And i tried using different form with different entity the problem was same
