### ISSUE TITLE
"An error occurred when verifying security for the message."

### ISSUE THREAD

**Issue by IanJuv** [AlexaCRM/integration-dynamics#16]
Hi! 

We've happily been using the CRM plugin for a month or two. Everything worked quite well from the get-go. However, since a few days, the connection suddenly dropped, while there were no changes made to either CRM or Wordpress.

The connection configuration page says:
_"An error occurred when verifying security for the message."_
![image](https://user-images.githubusercontent.com/31341025/29706150-0b38dfd4-8981-11e7-85ed-b92382c911c2.png)
As you can see, we're using Dynamics365 online and the user I'm using is a CRM sysadmin. 

I have found the following item on this particular message:
https://wordpress.org/support/topic/unable-to-set-the-crm-connection/

But to be honest, this doesn't help me in the slightest, I have no what clock to look at and I certainly have no control over a clock. How do I solve this? 

This is rather problematic, as we use the plugin the capture interested leads on our website. A mailing has gone out that points to a now defunct form. 

Thank you for you help!

**Comment by wizardist** [comment]
Hi @IanJuv,

Please provide your plugin version information.

**Comment by IanJuv** [comment]
Hi @wizardist,

That would be 1.1.32.5. Thx.

**Comment by wizardist** [comment]
@IanJuv iirc, MS guys have broken something in the authentication, please update your copy to 1.1.32.8 and try again!

**Comment by IanJuv** [comment]
I don't have WP rights on the plugin, but I'll figure it out. I'll try that and report back asap. Thanks for the quick response!

**Comment by IanJuv** [comment]
We had some issues updating the plugin, Wordpress stated that the "storage" folder already existed. So we tried uninstalling the plugin, removing leftover dirs from the /plugins/dynamics-integration/ folders.
That worked, but now we get the message:
_"Dynamics 365 Integration detected that /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/integration-dynamics/storage is not writable by the web server. Please fix it to complete the installation."_

It's strange, because we didn't have to change any permissions when installing the plugin the first time over. However, I assume this is something that we need to fix on our end, by chmod'ing the storage folder to allow writes through ftp. Was this added through a later update?

Alas, I don't have access to file directories via ftp, I've requested access. 

Am I making the correct assumption here?

**Comment by georged** [comment]
@IanJuv 

we've always had the requirement to write into /storage folder for logging and caching purposes. It sounds like your hosting provider has changed some of the settings for 3rd party plugins denying them write access to their own directories (some do to stop malicious plugins behaviors). Yes, we would need the write access for that folder.

Also, the issue is installation-related and not a bug in the source code per se. I'll be closing it here. If you still experiencing the issue after the reinstallation, please raise it on WordPress support: https://wordpress.org/support/plugin/integration-dynamics

Thanks
George
