### ISSUE TITLE
Can't upload images when plugin is installed.

### ISSUE THREAD

**Issue by hollykosec** [AlexaCRM/integration-dynamics#24]
We recently installed this plugin, but just discovered that we are getting the "HTTP error." message when we try to upload images with this plugin installed. Is there anything we can do to make the plugin "play nice"?

**Comment by georged** [comment]
Hi @hollykosec 

we need a bit more information to help. To start with, versions of WordPress you're using, our plugin version, php version if you have access to that.

Upload images where? In admin media interface? Using image handling in our plugin? Using some other plugin to upload images? If you use a third-party plugin for image upload, which one and what version?

Thanks
George

**Comment by hollykosec** [comment]
I don't see where I can download that version of the plugin. Everywhere it seems to still be 1.2.18.

<img width="2672" alt="screen shot 2018-12-17 at 12 09 07 pm" src="https://user-images.githubusercontent.com/45951456/50224055-81bf7f80-0362-11e9-83c4-5c02ebe5a7b4.png">
This is the error I get when trying to upload with the plugin enabled (see on the right).

What sort of access would you need? I can make a user for you, but IT has control of any access beyond that.

**Comment by georged** [comment]
Hi @hollykosec 

accessing WordPress as a user won't help us much, I'm afraid, we need administrative access to resolve the issue quickly. Is it possible? We can do a screenshare session if security is a concern.

In the meantime, please open settings for our plugin, click on About tab, change logging level to Debug. Reproduce the problem with the image, then go back to About tab of our plugin, change level back to Info, then download the log file and send it to support@alexacrm.com

Thanks
George

**Comment by wizardist** [comment]
Hi @hollykosec 

I think we can learn a lot about the issue with just a WordPress user. Could you create one for us and send the credentials to support@alexacrm.com as suggested by @georged?

Thanks

**Comment by hollykosec** [comment]
Thank you, I've sent an email!

**Comment by wizardist** [comment]
Hi @hollykosec 

We investigated and found a few issues.

Our plugin includes image upload functionality and, as part of this, it performs strict validations of permissions on the temporary folder used for image upload. Your PHP environment installation is slightly misconfigured and generates the following error: `is_file(): open_basedir restriction in effect. File(C:\Windows\Temp\phpA80C.tmp) is not within the allowed path(s): (d:\inetpub\wwwroot)`. 

Your administrators can fix that by adding the temporary folder (C:\Windows\Temp) to `open_basedir` in `php.ini`.

On our side we will try to fix this too.

**Comment by gearoidc** [comment]
Hi, we are having a similar issue with this plugin on WP engine

```

[Tue Jan 15 12:23:33.176121 2019] [:error] [pid 29211] [client 92.51.196.58:15357] PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /nas/content/live/COMPANYNAME/wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php on line 414, referer: https://www.COMPANYNAME.com/wp-admin/
[Tue Jan 15 12:23:40.178385 2019] [:error] [pid 29211] [client 200.68.128.89:52020] PHP Warning: file_get_contents(/nas/content/live/COMPANYNAME1/wp-content/uploads/wpcrm-storage/cache//config.783ed5c980105566598df20c3f2a9340.cache.ini): failed to open stream: Permission denied in /nas/content/live/COMPANYNAME/wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php on line 380
[Tue Jan 15 12:23:40.178615 2019] [:error] [pid 29211] [client 200.68.128.89:52020] PHP Warning: fopen(/nas/content/live/COMPANYNAME1/wp-content/uploads/wpcrm-storage/cache//config.783ed5c980105566598df20c3f2a9340.cache.ini): failed to open stream: Permission denied in /nas/content/live/COMPANYNAME/wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php on line 412
[Tue Jan 15 12:23:40.178708 2019] [:error] [pid 29211] [client 200.68.128.89:52020] PHP Warning: fwrite() expects parameter 1 to be resource, boolean given in /nas/content/live/COMPANYNAME/wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php on line 413
[Tue Jan 15 12:23:40.178755 2019] [:error] [pid 29211] [client 200.68.128.89:52020] PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /nas/content/live/COMPANYNAME/wp-content/plugins/integration-dynamics/src/Cache/PhpFastCache.php on line 414
```

Any idea / help 
thanks

**Comment by georged** [comment]
Similar issue as in you cannot upload the images? Or something else? We have a number of customers using WPEngine, sounds like a localized issue for a specific deployment.

**Comment by gearoidc** [comment]
Thanks @georged for getting back. WP Engine made similar changes to php.ini but did not make a difference, we have disabled your plugin to see if that helps but it does not. Debugging this more.

**Comment by gearoidc** [comment]
@georged you can close this again, we found the issue and was on our end. It was a misconfiguration, our live site was referencing the devs site upload path.

**Comment by georged** [comment]
Awesome, glad to hear it's resolved!
