### ISSUE TITLE
Class 'Memcache' not found in PHP 7.3

### ISSUE THREAD

**Issue by tmszyman** [AlexaCRM/integration-dynamics#25]
Hi, we're using PHP 7.3 and this plugin breaks the website. In PHP 7.2 there is default module memcached instead of memache. Do you consider an update? Or it can be changed manually?

**Comment by tmszyman** [comment]
We set manually "memcached" in the options and it's working

**Comment by georged** [comment]
Hi @tmszyman 

we do use WordPress cache if it's available and test for the memcache support by checking for the presence of `memcache_connect` function. Looks like your environment does contain this function but does not support `memcache`.

There is an option to force specific caching mechanism, let me check with the crew.

Thanks
George

**Comment by georged** [comment]
Looks like you found the option - great!
Let us know if you need any further assistance
George

**Comment by tmszyman** [comment]
@georged Is it possible to set option $storage to the "memcached" in the _PhpFastCache_ class outside the plugin? Because we edited source files, but it would be removed with the next update.

I'm talking about the file _PhpFastCache.php_.

**Comment by wizardist** [comment]
Hi @tmszyman 

Could you try this?

1. Revert the changes in `PhpFastCache`
2. Add a snippet to your `functions.php`:

```php
add_action( 'wordpresscrm_before_load', function() {
  \AlexaCRM\WordpressCRM\Cache\PhpFastCache::$storage = 'memcached';
} );
```

What it should do is change the `$storage` static member to the desired value without actually tampering with files.

Hope that helps.

**Comment by tmszyman** [comment]
@wizardist Thank you, it works. ;)
