### ISSUE TITLE
Unable to connect to Dynamics 365 when AzureAD tenant have basic auth blocked

### ISSUE THREAD

**Issue by JankeSkanke** [AlexaCRM/integration-dynamics#26]
Recommended security practice for AzureAD today is to block Basic Auth. Do you have any immediate plans to update the wordpress plugin to support Oath tokens (Modern Auth) ?

**Comment by georged** [comment]
Hi @JankeSkanke 

the next major version of the plugin will switch to web api and will support S2S authentication. You can see how we support it in the [new toolkit](https://github.com/AlexaCRM/dynamics-webapi-toolkit).

Cheers
George

**Comment by JankeSkanke** [comment]
Thank you for the quick reply. Looking forward to the release and hoping it is not far away.

**Comment by JankeSkanke** [comment]
Any new information about this - I still dont see any option to use App Based authentication in Azure AD. (I create a client app with a secret (OAtuh)) for accessing Dyn365CRM

**Comment by georged** [comment]
@JankeSkanke new plugin is already [available](https://wordpress.org/plugins/integration-cds/), it's based on the [new toolkit](https://github.com/AlexaCRM/dynamics-webapi-toolkit) and supports client id/secret authentication. It's been rewritten from scratch to deliver smaller memory footprint, better performance, and reliability. Premium version supporting authentication and tons of other goodness will be available very soon.
HTH
George
