### ISSUE TITLE
Verification of fields

### ISSUE THREAD

**Issue by red436** [AlexaCRM/integration-dynamics#27]
It seems people are able to submit empty forms to the plugins endpoint.
If there is a way to stop this already please let me know.

**Comment by georged** [comment]
@red436 this is extremely vague. Can you provide any tangible examples? For example, a url to a page where blank submissions are accepted. You can email the url to support@alexacrm.com if you have any privacy concerns.

**Comment by red436** [comment]
I apologize I found FormValidator.php. We were getting empty records in Dynamics. I had recently installed the plugin and thought this was the source.
Thank you for your great work.
