### ISSUE TITLE
Inline view templates are not supported in this version

### ISSUE THREAD

**Issue by jkingMDH** [AlexaCRM/integration-dynamics#3]
Hello, 

When I try to use the inline template with CRM view, using the example provided in the documentation, I get the error "Inline view templates are not supported in this version" 

I currently have Wordpress 4.6.1 and PHP 5.4

Is there anything I need to change on my end?

**Comment by jkingMDH** [comment]
I just updated to PHP 7.0 and still received the same message.

**Comment by georged** [comment]
Hi jkingMDH,

apologies for slightly misleading message. What it's meant to say that inline view templates are not supported in this _version of the plugin_. We have premium addon coming that will support inline templates.

If you'd like to be notified when it's available, shoot email to support@alexacrm.com and we'll make sure you're the first to know.

Thank you
