### ISSUE TITLE
Error: Could not find CreateResponse node in XML returned from Server

### ISSUE THREAD

**Issue by Ojala67** [AlexaCRM/integration-dynamics#31]
Hi,
I installed the Dynamics 365 Integration Plugin.
It works fine for all entities except for leads.
This is the code which I used:

[msdyncrm_twig]
{% form entity=”Lead” name=”Lead” mode=”create” %}{% endform %}
[/msdyncrm_twig]

I’m getting this error:
Error: Could not find CreateResponse node in XML returned from Server

Some background. I created a custom solution in dynamics and the only entity which I customised was the leads entity. Not sure if this has anything to do with it.

Any ideas?

Thanks.

**Comment by georged** [comment]
@Ojala67 please use https://wordpress.org/support/plugin/integration-dynamics/ forums for support.
