### ISSUE TITLE
Handles Cases?

### ISSUE THREAD

**Issue by Matt2012** [AlexaCRM/integration-dynamics#6]
Will or does the wordpress plugin handle retrieving and updating cases?

**Comment by georged** [comment]
It does support retrieval and updating of any entity including cases. You need to use [msdyncrm_view] shortcode to display a list of cases and [msdyncrm_form] shortcode to create/edit individual case record. See [documentation](http://docs.alexacrm.com/wpcrm/) (work in progress)

**Comment by Matt2012** [comment]
Great - my client has documents from Sharepoint Online / 365 in the Dynamics CRM associated with those case. Would those be retrievable & downloadable too?

Any news on premium version & pricing?

**Comment by georged** [comment]
@Matt2012 we expect to ship premium version in couple weeks, please register [here](http://alexacrm.com/dynamics-crm-integration-premium/) to get notified.

Support for SharePoint documents is on a roadmap, quite a few people asked about it. Once we over the hill with the premium, we'll be providing some visibility into the feature. Not sure 100% if it's our plugin "responsibility" to handle SharePoint documents but, regardless of that, we'll definitely provide some ideas and considerations for the implementation.

**Comment by Matt2012** [comment]
@georged I think the issue is that although I can query sharepoint directly for documents I need to associate them with cases. So I think the integration is pretty essential for my use case.
Have you scoped whether it is even possible using the APIs that your library exposes?

**Comment by georged** [comment]
@Matt2012 
website, plugin and toolkit aside, can you currently associate SharePoint documents with a case in CRM? Whatever is the association mechanism, you'd have some records in CRM that would give you a URL for a SharePoint document(s). Our toolkit would allow you to get that URL but we don't provide any means to retrieve the document from SharePoint as it's outside of CRM.

**Comment by Matt2012** [comment]
Great - do you have a timescale / pricing on premium yet?

**Comment by georged** [comment]
@Matt2012 as per above: we expect to ship premium version in couple weeks, please register [here](http://alexacrm.com/dynamics-crm-integration-premium/) to get notified.
