### ISSUE TITLE
Cannot resolve CRM region

### ISSUE THREAD

**Issue by jsbishop1** [AlexaCRM/integration-dynamics#7]
I've received the following message in the Wordpress Connection screen:
"Cannot resolve CRM region: check CRM server url"

Is this because our Dynamics instance is hosted on a .com.au domain?

Thanks.

**Comment by georged** [comment]
@jsbishop1 Sounds like you are selecting CRM Online as the deployment type but then entering custom URL for the CRM organization. Please change deployment type to On-premises and try again.

**Comment by jsbishop1** [comment]
Thanks george. All good.
