### ISSUE TITLE
Add support for AD authentication

### ISSUE THREAD

**Issue by georged** [AlexaCRM/integration-dynamics#8]
At the moment only CRM Online and IFD deployments are supported

**Comment by rish501** [comment]
Hi
Any progress on this?
I understand it's not good practice, but is there a way I can modify the code to use an AD username to connect?

**Comment by georged** [comment]
Sorry, not really as there is little to no demand for the feature with the strong push to Dynamics 365 online. In general, placing WordPress on the same network as your Dynamics CRM is just not a good idea from the security point of view.

Good practice is to fork the project, do whatever changes you want and then submit the pull request. It's an open source project, you can do whatever you want :)
